drop sequence badsort_seq;
drop table badsort_parameter;
drop table badsort_usage;
drop table badsort_table;
drop table badsort_index;
drop table badsort_mapping;
drop table badsort_module;
drop table badsort_sql;
drop table badsort_plan;
